[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@velodrome/=lib/relay-private/lib/contracts/"
]

fs_permissions = [{ access = "read-write", path = "./"}]

solc-version = "0.8.19" 